default: &default
  reconnect: false
  adapter: mysql2
  username: root
  password: 2bF1R3tA
  host: localhost
  pool: 5
  port: 3306
  timeout: 5000

development:
  <<: *default
  database: ficha2_dev

test:
  <<: *default
  database: ficha2_test

production:
  <<: *default
  database: ficha2_production
