# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  reconnect: false
  adapter: mysql2
  username: root
  password: 
  host: localhost
  pool: 5
  port: 3306
  timeout: 5000

development:
  <<: *default
  database: ficha2_dev

test:
  <<: *default
  database: ficha2_test

production:
  <<: *default
  database: ficha2_production
